### ISSUE TITLE
Professional editing [$38] {1000•CFS} {10000•CPAPER} [$38]

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/paper.cyber.fund#1]
Paper was written by non native speakers and have a lot of grammatical mistakes and some time holly mess. We need help to edit it. 
In accordance with [Term of Genesis Sale Race](http://paper.cyber.fund/en/genesis_sale_race.html) there is additional bounties:
- **1000 [cyber•Shares](https://www.coinprism.info/asset/3BUQAssohZgE13keAeRTgy5jnGSHR1v119)**,
- **10000 [cyber•Paper](https://www.coinprism.info/asset/3DjkWRozRLyHNRLixD9YR9tqREaYuBR4de)** shares.

**Comment by DevsDoingDev** [comment]
is this still available?
